version: '3.8'
services:
  questdb:
    ports:
      - '9000:9000'
    networks:
      - infra
  api:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - ./app/node_modules
    depends_on:
        questdb
    networks:
      - infra
  client:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/app
      - ./app/node_modules
    depends_on:
      - api
    networks:
      - infra

networks:
  infra:
  
